const constants = {
  SET_AUTH_DATA: "SET_AUTH_DATA",
  SET_MESSAGE: "SET_MESSAGE",
  SET_MESSAGE_DATA_LIST: "SET_MESSAGE_DATA_LIST",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
};

export default constants;